### ISSUE TITLE
Dynamic Device Detection

### ISSUE THREAD

**Issue by ChekTek** [sergey-tihon/streamdeck-homebridge#1]
It looks like only Homebridge configured devices are available in the property inspector dropdown. Is it possible to add dynamically added devices?
![image](https://user-images.githubusercontent.com/6678919/151875859-7dd8cbb3-55ca-43cf-b511-05a86622704f.png)

**Comment by sergey-tihon** [comment]
I am not sure that I fully understand what it is `dynamically added devices`
but I prepared some fixes #2 that

show devices outside of room layout
<img width="279" alt="image" src="https://user-images.githubusercontent.com/1197905/151946388-0e3d4e1b-de06-44b0-8d3a-32f4781cff38.png">

show loading indicator when plugin wait for Homedridge API response
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1197905/151946567-5fb361f4-3f24-4d24-bcdd-58792293fc4a.png">

during the loading list of accessories is empty and I hope this is the reason why you may see empty list.

[Compiled plugin](https://github.com/sergey-tihon/streamdeck-homebridge/suites/5133631756/artifacts/154595680) available in [CI build artefacts](https://github.com/sergey-tihon/streamdeck-homebridge/actions/runs/1777497466)

**Comment by Adelz89** [comment]
![Screenshot 2022-02-03 190743](https://user-images.githubusercontent.com/98969790/152381397-8b4a1d3c-03b4-40c3-9b50-62f0438d8edc.png)

i can't chose switch

**Comment by sergey-tihon** [comment]
@Adelz89  what version of plugin do you have installed? 1.1.0 from the store or 1.2.0 from CI (my prev comment)

**Comment by Adelz89** [comment]
> @Adelz89 what version of plugin do you have installed? 1.1.0 from the store or 1.2.0 from CI (my prev comment)

1.1.0 from the store

**Comment by sergey-tihon** [comment]
@Adelz89 please try this version - https://github.com/sergey-tihon/streamdeck-homebridge/suites/5133631756/artifacts/154595680

If it does not solve your issue I'll continue searching for a reason

**Comment by ChekTek** [comment]
The new version seems to be finding the devices that were missing before 👍
