### ISSUE TITLE
Unnecessary Google spyware

### ISSUE THREAD

**Issue by ohmantics** [sergey-tihon/streamdeck-homebridge#20]
Does a Stream Deck plugin really need to be phoning home to Google?

(Also, shame on Elgato for not policing the plugins they suggest.)

**Comment by sergey-tihon** [comment]
> Does a Stream Deck plugin really need to be phoning home to Google?

If you're asking, "Does any piece of software needs Telemetry?" then the short answer is "Yes".

p.s. So afaik, ga should not be used in the latest version, most likely if you set up a proxy you should not find any call to google analytics from this plugin.

**Comment by sergey-tihon** [comment]
Fixed in [v1.4.0](https://github.com/sergey-tihon/streamdeck-homebridge/releases/tag/1.4.0)

**Comment by ohmantics** [comment]
Thank you!
