### ISSUE TITLE
Configuration not possible

### ISSUE THREAD

**Issue by docb7** [sergey-tihon/streamdeck-homebridge#30]
Hi, I try to use your plugin, but unfortunately I cannot configure it. When I try to use a switch, there are no input fields for server-address, etc. - see picture. I just installed the plugin and did nothing else. I use a Mac with an M2. 
Would be great if you could help me.
Best
b

<img width="546" alt="image" src="https://user-images.githubusercontent.com/34217688/235309755-9da1268b-c192-4c11-86a5-d76373179620.png">

**Comment by sergey-tihon** [comment]
Most likely it due to M2 chip - please try Rosetta mode - https://github.com/sergey-tihon/streamdeck-homebridge/issues/18#issuecomment-1398937173
