### ISSUE TITLE
seems very unhappy with ip starting with 10.0.0.x

### ISSUE THREAD

**Issue by fiveyearss** [sergey-tihon/streamdeck-homebridge#34]
![image](https://github.com/sergey-tihon/streamdeck-homebridge/assets/63285579/70cfaebd-b1ea-44cf-94f4-aec910ace070)
just throws a huge error

**Comment by fiveyearss** [comment]
im running a homebridge server on a raspberry pi on my local network

**Comment by sergey-tihon** [comment]
can you open the same url in browser and login?

**Comment by fiveyearss** [comment]
@sergey-tihon yes, http://10.0.0.2:8581/ opens up my homebridge UI for me and i can log in

**Comment by sergey-tihon** [comment]
Please try without trailing /, just http://10.0.0.2:8581

**Comment by fiveyearss** [comment]
the slash was my issue sorry for the confusion

**Comment by sergey-tihon** [comment]
Anyway, thank you for reporting this issue. It will be auto-removed in the next version
