### ISSUE TITLE
I can login, but that's all

### ISSUE THREAD

**Issue by johnnygoodface** [sergey-tihon/streamdeck-homebridge#40]
I'm using 1.4 and I can login (for a switch control) but after that I can't get the list of accessories anymore: it shows "Default Room" when I click on the "Accessory:" dropdown and that's all, no accessory. I'm on MacOS 14.5, and using Stream Deck 6.7.0. Homebridge is on my Synology NAS and firewall is off. 
<img width="527" alt="SCR-20240801-osqf" src="https://github.com/user-attachments/assets/4b8e1cff-d4e2-4708-a21a-c669576c2cfc">

**Comment by johnnygoodface** [comment]
Any developments on this issue

**Comment by sergey-tihon** [comment]
What Homebridge version do you have? (Sometimes Homebridge update and restart helps)

**Comment by johnnygoodface** [comment]
I got 2 different versions: one from the NAS itself, and one from the HB interface:
<img width="472" alt="SCR-20240918-kxwf" src="https://github.com/user-attachments/assets/550b4356-75e7-498a-927e-53efa5eef27e">
<img width="334" alt="SCR-20240918-kxzb" src="https://github.com/user-attachments/assets/2f826dfe-0ed7-4bf4-a618-de9bd8bf55a8">

**Comment by sergey-tihon** [comment]
Looks like the last version v1.8.4

you may try to install latest build https://github.com/sergey-tihon/streamdeck-homebridge/actions/runs/10642928056/artifacts/1877361955 from [artifacts](https://github.com/sergey-tihon/streamdeck-homebridge/actions/runs/10642928056) ...

can you try to scroll inside the dropdown list? Maybe devices are actually there and it is weird UI issue

**Comment by johnnygoodface** [comment]
Just tried your latest build
I can logon fine, but I got the same result:
<img width="519" alt="image" src="https://github.com/user-attachments/assets/ef389306-7cf0-4d1a-8671-d2b7c348e44e">
The dropdown only contains the "Default Room" item (which I can't select anyway) and nothing else

**Comment by sergey-tihon** [comment]
Can you share screenshot of your Accessories screen from Homebridge ?

This dropdown should mimic your room/characteristic structure from Accessories screen.

**Comment by johnnygoodface** [comment]
Wow! It's as dark as the night sky! I've got no Accessories listed there! That's very odd. Let me debug that.

**Comment by johnnygoodface** [comment]
'was an issue with my NAS firewall! Turned it off, then back on. Then I re-added your streamdeck switch control. Now I can see all my accessories in the drop down. I should have guess. Thank you for your help :)

**Comment by sergey-tihon** [comment]
I'm glad that you figured it out. It was not obvious.
