### ISSUE TITLE
Missing most of my devices after login

### ISSUE THREAD

**Issue by ToBro14** [sergey-tihon/streamdeck-homebridge#6]
**My system uses:**
streamdeck-homebridge Plugin version 1.3.1
Streamdeck version 5.2.1
macOS 11.6.4
Homebridge v1.4.0.

The plugin used to work fine before but now it only shows 2 or 3 out of my many devices in homebridge.
I'm still able to login to homebridge in the button config.
I guess it stopped working with the latest plugin update, but I'm not sure.

**Comment by sergey-tihon** [comment]
> The plugin used to work fine before but now it only shows 2 or 3 out of my many devices in homebridge.

Do you see all you devices in Homebridge UI? Have you tried reboot you Homebridge server?

I also had issues with `Homebridge v1.4.0` and have to reinstall some plugins and even Homebridge.

**Comment by sergey-tihon** [comment]
Close this issues as not active.
