### ISSUE TITLE
State should update periodically 

### ISSUE THREAD

**Issue by myMartek** [sergey-tihon/streamdeck-homebridge#7]
I noticed that when changing a state value externally (eg from iPhone) the Stream Deck is not updated at all.

I would love when I could set an interval per button at which the button should recheck the current state (eg. every 1, 2, 5, 10, 60 ... seconds)

**Comment by sergey-tihon** [comment]
> I noticed that when changing a state value externally (eg from iPhone) the Stream Deck is not updated at all.

Yes, current version does not check for updates.

> I noticed that when changing a state value externally (eg from iPhone) the Stream Deck is not updated at all.

I am not sure about independent updates configurations. Technically possible to request all statuses in one call, so it should be possible to update all statues together.

Where do you place you Homebridge action button? Main screen or inside profile/folder?

There is an event on potentially allow update statuses before button will appear on Streamdeck.
https://developer.elgato.com/documentation/stream-deck/sdk/events-received/#willappear

**Comment by sergey-tihon** [comment]
Implemented in [v1.4.0](https://github.com/sergey-tihon/streamdeck-homebridge/releases/tag/1.4.0)
